/**
 * GHF_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductServiceCategoryDto { 
    product_Service_Cate_ID?: string | null;
    product_Service_Cate_Name?: string | null;
    status?: boolean | null;
    position?: number;
    update_By?: string | null;
    update_Time?: string | null;
    checked?: boolean;
}

