/**
 * GHF_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleUserDto { 
    user_Account?: string | null;
    role_Unique?: string | null;
    role_Name?: string | null;
    role_Type?: string | null;
    role_Sequence?: number;
    status?: boolean;
}

