// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace API.Models
{
    public partial class Product_Service_Category
    {
        [Key]
        [StringLength(20)]
        public string Product_Service_Cate_ID { get; set; }
        [Required]
        [StringLength(254)]
        public string Product_Service_Cate_Name { get; set; }
        public bool? Status { get; set; }
        public int Position { get; set; }
        [StringLength(50)]
        public string Update_By { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Update_Time { get; set; }
    }
}